apiVersion: v1
kind: Service
metadata:
  name: nginx-clusterip-svc
  labels:
    app.k8s.io/name: nginx-svc
  namespace: giropops
spec:
  selector:
    app.k8s.io/name: nginx-svc
  ports:
    - port: 80
      name: http
      targetPort: 80
  type: ClusterIP
      
