FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY ./ .

RUN dotnet publish -c Release -o /app/out

FROM alpine:3.15.9
WORKDIR /app	

COPY --from=build /app/out .

ENTRYPOINT ["./mvc-app"]

# SIZE 216MB
# 13.9, quando mudei p alpine