FROM alpine:3.20

RUN apk update \
    && apk upgrade \
    && apk add --no-cache dotnet6-sdk

ENV DOTNET_URLS=http://+:5000

WORKDIR /app

COPY ./ .

RUN dotnet restore
RUN dotnet publish -c Release -o out

ENTRYPOINT ["out/mvc-app"]

# SIZE 536MB
