FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /app

COPY ./ .

RUN dotnet publish -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:6.0-alpine
WORKDIR /app	

COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "./mvc-app.dll"]

# SIZE 216MB
# 13.9, quando mudei p alpine
