apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-deployment
  name: nginx-deployment
  namespace: giropops
spec:
  replicas: 20
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxSurge: 1
      maxUnavailable: 2
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx-deployment
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          limits: 
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: 0.25
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 80
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 5
          initialDelaySeconds: 10
        readinessProbe:
          exec:
            command: 
            - curl
            - -f
            - http://localhost:80
          periodSeconds: 10
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 2
          initialDelaySeconds: 10
      - image: redis:7.2
        name: redis
        ports:
        - containerPort: 6379
        resources:
          limits: 
            cpu: "0.5"
            memory: 256Mi
          requests:
            cpu: 0.5
            memory: 128Mi
        livenessProbe:
          tcpSocket:
            port: 6379
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          initialDelaySeconds: 10
