apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: web-server
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        root /usr/share/nginx/html;
        index index.html index.html;
      }
      location /metrics {
        stub_status on;
        access_log off;
      }
    }
