apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
  namespace: web-server
spec:
  type: NodePort
  ports:
    - port: 9113
      targetPort: 9113
      name: metrics
  selector:
    app: nginx
