apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    storage: local
  name: giropops-pv
  namespace: giropops
spec:
  capacity:
    storage: 15Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data
  storageClassName: giropops
