apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    pvc: giropops-pvc
  name: giropops-pvc
  namespace: giropops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: giropops
  selector:
    matchLabels:
      storage: giropops-pv
